name: Pull Request2

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn
      - name: Spin up test database
        run: docker-compose up -d
      - name: Wait until database up and running
        run: docker ps -a
      - name: Prisma migrate
        run: yarn prisma migrate dev
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5433/test-db
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build