name: Pull Request

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    env:
      DATABASE_URL: postgres://postgres:password@localhost:5432/test-db
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn
      - name: Spin up test database
        run: docker-compose up -d
      - name: Prisma migrate
        run: yarn prisma migrate
      - name: Test
        run: yarn test
        